- README.md
- slack.py
Now uses ~/.slackcattoken. Also exists gracefully on file not found.
Added firefox specific instructions for obtaining the token as well as explaining what file to put it in.
> removed hard coded slack token file

- slack.py
Generated on upload… let's just use the event when the files are shared on
some chat instead.
> Ignore file_public

- slack.py
For some obscure reason, deleting a file on slack causes a message_deleted event with
an empty text, so this ignores them.
> Ignore file deletion messages

- irc.py
When channels are not being autojoined at start, add them to the parted list
so that they get completely ignored until they are joined on IRC.
This closes #80
> Add all channels to parted list

- slack.py
- slackclient/client.py
- slackclient/server.py
Remove the original reconnect code from the slack module and just do it all in one place.
Raise exceptions all over the place rather than try to hide them.
> Manage reconnect in one place

- irc.py
If more slack events were stuck in the queue, they'd be missed due to the socket
not being marked as readable anymore.
> Loop until there are no more slack events

- irc.py
- slack.py
Due to the one to one mapping of service instances to listen ports /
tokens, being able to pull the most commonly adjusted config arguments
straight out of the environment will be really handy, especially for
those of us who use a lot of process supervision.
This necessitated moving token file parsing out of slack.py and into
irc.py in addition to modifications to the argument handling.
Something to keep in mind: as written this commit changes precedence so
that if PORT or TOKEN are set their corresponding optargs are ignored.
To switch that order around, add a second test to see if args.token or
args.port are set to their defaults and only apply the environment value
if the arg values are still default.
> startup: support environment variables for PORT and TOKEN.

- irc.py
For whatever reason, the slack I'm on has users named "a" and "t", so chat looks like "can'@t run @a test" without this patch.
> Don't prefix short nicknames with @, since the user is probably just using it as a word

- irc.py
- man/localslackirc.1
- slack.py
- slackclient/client.py
When a `xoxc` token is in use, the cookies are required too to authenticate.
The initial input for this solution comes from here: https://b17zr.com/2019/10/09/download-custom-slack-emojis/
> Support for the new xoxc tokens

- requirements.txt
Closes: #165
The debian and the pypi package are not named the same it seems…
> Fix wrong name

- irc.py
Topic can't be changed on group chats. Do not crash in case.
> Do not crash when a topic change fails

- debian/changelog
- debian/control
- requirements.txt
It will fail if people use older versions that are around on
ubuntu and debian or their manual installs.
This will force them to upgrade before localslackirc fails to work.
> Require typedload 2

- README.md
It goes from installing, grabbing the token and then configuring the irc client
stuff are less all over the place.
> Make README more linear

- CHANGELOG
- debian/changelog
- debian/control
- requirements.txt
- slack.py
Nothing against it, but it's not in the stdlib and since
I moved to using py3.8 anyway for the Literal, might as well
use dataclass.
Not as powerful but with a nicer syntax and, most importantly, in the
stdlib.
> Do not depend on attrs

- debian/changelog
- debian/control
Had to do a debian release because i made a mistake.
Basically with make test, unlike mypy, everything gets imported for
real, so the modules are needed also on the build agent.
> Pick the debian-only fix

- CHANGELOG
- irc.py
- slack.py
- tests/test_re.py
Prior to this mentions were inserted looking for them with a
regex like <word-separator>username<word-separator>
This worked but in the case of http.//username/ it would match.
The new regex searches for an initial and optional sequence of "://"
(to match any url schema) followed by any number of non space characters
and then with the old regex at the end.
So URLs still match but their match is different so they can be skipped.
This further changes the match, instead of creating one regex per username
only one giant one is created, putting in OR all the patterns for all the
usernames.
Because the regex is only ran once the substitution is performed
right to left, in order to preserve the position of the matches.
Closes: #81
> Do not insert mentions in URLs

- CHANGELOG
- irc.py
- tests/test_re.py
Refactor how tagging users is done.
Now instead of using a global regexp with all of the users, regexps are created on a per-channel basis and only contain the users in that channel.
On private discussions users are no longer tagged in any case.
To invite users to a channel, the `/invite` command works fine.
Internally, the regexps are cached and reused instead of being recompiled every time. They are automatically dropped when a user joins/leaves a channel.
> Tag only users on the same channel

- slack.py
When the history missing is too much, just download the final 4 days.
This is because otherwise slack will send the older history and then
not send the more recent one.
So I believe it is better to have the recent one instead.
Fixes: https://github.com/ltworf/localslackirc/issues/218
> Limit backlog download to 4 days

- CHANGELOG
- slack.py
Since slack completely ignores the limit parameter set to 1000, this seems to be needed.
Also, for this API they seem to always send a cursor, but use an empty string, rather than not setting the cursor at all.
Just in case, I test for both things.
> Use cursor for conversations.list API

- CHANGELOG
- README.md
- irc.py
- localslackirc.d/example
- man/localslackirc.1
- tests/test_re.py
This is to avoid off topic channels in which coworkers will
invite you over and over, no matter if you keep leaving them,
refusing to take the hint that one does not wish to be in that
channel.
The channels will be joined on slack but not joined on IRC, so the
coworkers will be happy, and so will you.
No message will be received from those channels, unless you /join
them again.
In no case will chat history be fetched for those channels.
> Ignore some channels despite autojoin

- irc.py
Slack will send the unicode name, that might not work in IRC.
So instead, use the channel ID to fetch the normalised ASCII name.
> Use normalised name for channel mentions

- README.md
Was setting up multiple bridges for multiple teams today and found it would give the same token every time (the first one in the list). 
I ended up just dumping the JSON object and getting the tokens that way, but for most users running in a private window would be easy and do the trick.
> Add note if there are multiple teams when getting token

- CHANGELOG
- irc.py
- localslackirc.d/example
- man/localslackirc.1
- tests/test_re.py
Formatted text longer than a certain amount can now be saved as .txt files in a chosen directory, to be more readable and avoid the wall of text in the chat
> long formatted text into files

- irc.py
- localslackirc.d/example
- log.py
- man/localslackirc.1
- slack.py
This avoids having to hack slack.py to debug incoming messages from
slack. Instead, one can just set DEBUG to anything in the configuration
file to turn debugging on.
> slack: allow debugging incoming events without hacking the source

- diff.py
- tests/test_diff.py
```
a = 'il numero dei fili'
b = 'il numero massimo dei fili'
out = 's/numero dei/numero massimo dei/'
```
So it is no longer considered an append
> Improve diff

- CHANGELOG
- irc.py
- localslackirc.d/example
- man/localslackirc.1
- tests/test_irc.py
- tests/test_re.py
Fixes: #296
Some people can't understand that continuously using @channel mentions
to ask a question to one specific person is somewhat annoying and
distracting.
Since fixing people is much harder than coding, this adds some code to
ignore the general mentions by those people.
> Add new setting for silenced yellers

- requirements.txt
Unfortunately, upstream changed API and didn't even
include a changelog.
Well it seems he was not even aware of having changed API.
Anyway for now pin it at least until debian gets released
and upgrades it on debian, then I can just move to the new
one and force version >=9
Fixes: #304
> Pin library version

- irc.py
- tests/test_irc.py
Sometimes URLs come with a label that is exactly the same URL again.
Don't expand those URLs as label¹, then ¹ URL because that is just
unecessary noise.
> irc: don't expand URLs with no meaningful label

- slack.py
As they document, ignore this useless event.
> gnore accounts_changed

- debian/changelog
- debian/tests/control
Tests failing can block mypy from migrating, thus preventing the usual FTBFS error
> Add debian testsuite

- irc.py
- slack.py
Basically the file shared event contains information about which channel is receiving the file but not
if the file is referenced into a thread or in the main channel.
This changes a bunch of things.
No longer handle the FileShared event at all, but instead read the files field in messages and
get the links from there.
So the announce is no longer needed to create a fake message and file_shared events are ignored.
Doing this, automatically the shared files end up in their right place.
Also the call to get file information is no longer needed and was removed.
Closes: #342
> Refactor handling of attached files

- debian/changelog
- debian/tests/control
Not tagging it, binary is unchanged.
> Point release to fix autopkgtest

- CHANGELOG
- irc.py
- slackclient/client.py
Just always use asyncio signals.
Do not block the async loop when waiting for a connection.
Always use the same async loop, do not end it to start a new one when
the irc client reconnects.
Make the websocket closing timeout very small, or that hangs termination
for 10 seconds for no useful reason.
> Improve handling of unix signals

- slack.py
I was seeing an infinite loop when localslackirc was trying to display the history from a particularly busy channel. After adding some debugging log calls in there, I noticed that the same cursos was being returned over and over, causing an infinite loop.
> Prevent loop when processing history

- msgparsing.py
We call `emojize` with a `language` argument not handled in the dummy definition of the function. To prevent other problems in future, ignore every other arguments than `string`.
> fix compatibility when python3-emoji isn't installed

- slackclient/client.py
Hi,
I've had localslackirc crash with the following backtrace:
```
Traceback (most recent call last):
File "_venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 959, in transfer_data
message = await self.read_message()
File "_venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1029, in read_message
frame = await self.read_data_frame(max_size=self.max_size)
File "_venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1104, in read_data_frame
frame = await self.read_frame(max_size)
File "_venv/lib/python3.10/site-packages/websockets/legacy/protocol.py", line 1161, in read_frame
frame = await Frame.read(
File "_venv/lib/python3.10/site-packages/websockets/legacy/framing.py", line 68, in read
data = await reader(2)
File …
```
> Fix passing websocket connection timeout on RTM reconnects

- CHANGELOG
- debian/changelog
- irc.py
- slack.py
This avoids to fetch all the channels for the history and just obtains
the joined ones.
Closes: #440
> Fix for the rate limiting problem
