ltworf/localslackirc

irc.py
added required argument that I erroneously removed in my previous pr.
=> fixed crash in whohandler

requirements.txt
=> Fix requirement on websocket-client.

irc.py, slack.py
=> Don't include disabled user in /names.

slack.py
quick fix to send slackbot responses to the client, fixes #4.
=> send slackbot responses to client

docker/Dockerfile
NOTE: See code for risks about this
Add certs into the docker
=> Let the daemon to listen on 0.0.0.0 inside docker.

irc.py
Since people keep adding me to channels that I have no interest in, and since
in slack even if I leave them they can just add me back; this allows the IRC
client to part said channels and from then on, ignore whatever is received from them.
It is temporary and gets forgotten on restart.
=> Handle PART command

irc.py
=> Do not hardcode hostname

irc.py, slack.py
Because slack graciously changed the API for how files are uploaded.
=> New file API

irc.py
Instead of giving up, on network errors and such
=> Keep retrying forever

CHANGELOG, README.md, irc.py, slack.py, slackclient/client.py, slackclient/slackrequest.py
Closes: https://github.com/ltworf/localslackirc/issues/19
=> file upload

irc.py, slack.py
This lets new joins to be notified.
Also, for big channels, this lets the users to be reported in chunks rather than all at once or nothing.
=> Join users to channels

slack.py
`channels.list`, `mpim.list`, `groups.list` are all [deprecated](https://api.slack.com/methods/groups.list) and have been collapsed into `conversations.list`. Also the old APIs were not filtering out archived mpim's.
This PR uses the new API and should apply filtering correctly.
=> Use conversations.list instead of deprecated APIs.

irc.py, slack.py
Caches timestamps of sent messages.
=> Sent cache

rocket.py
Craft a special id to recognise them.
=> Do not show self messages, on rchat

slack.py
When sending messages from other clients,
prepend them with a message and pretend that they are
sent by the other user in the query. Kind of like what
the original slack gateway was doing.
=> Put own messages from other clients in the correct query

irc.py, rocket.py
They seem to improve the rchat situation, since it's the branch I normally use.
=> Merge some more rchat fixes into master

irc.py, rocket.py, slack.py
=> Handle actions

CHANGELOG, debian/changelog
=> New version

CHANGELOG, irc.py, rocket.py, slack.py
=> Invite support

irc.py
Fix PRIVMSG so they are addressed to the local user and not the sender.
From the RFC:
:Angel!wings@irc.org PRIVMSG Wiz :Are you receiving this message ?
; Message from Angel to Wiz.
=> Fix PRIVMSG

irc.py
So I know more of what is going on. No point in logging it
and not showing to the user.
=> Show the actual exception

debian/changelog, debian/control
Fix debian stuff to do a new release.
=> New release

irc.py, localslackirc.d/example, man/localslackirc.1, systemd/localslackirc@.service
So the "config file" I use with systemd can configure everything.
=> Add all the parameters as env vars too

irc.py
I don't actually know if this software has ever been tested on windows,
but in theory it should work, so let's not be bad and keep it multi
platform.
=> Skip su() on windows

.travis.yml, CHANGELOG, README.md, debian/changelog, debian/control, mypy.conf, requirements.txt, rocket.py, slack.py
To be able to parse events without using the massive if block
=> use Literal

CHANGELOG, irc.py, localslackirc.d/example, man/localslackirc.1, rocket.py, slack.py, systemd/localslackirc@.service
This is to add support to get the messages that were exchanged while offline.
=> Chat history

irc.py, localslackirc.d/example, systemd/localslackirc@.service
A couple of issues that both made the status file not work with systemd.
=> Handle signals

slack.py
The last message seen is sent again with the history, since it has the last
seen timestamp.
So this commit ignores that message.
Also to avoid the history to start again from the same point in time at
the next reconnection, if no new messages were sent, this considers
the timestamps in the history messages as the latest timestamp so
that they won't be requested again to slack.
=> Improve the history feature

slack.py
Sometimes it seems to not work.
=> Add more logging about the history feature

slack.py
Closes #187 
Fetch the history of subthreads when reading the chat history.
=> Thread history

irc.py
=> Hold events from slack if there is no IRC client

CHANGELOG, irc.py
Handle more exceptions with non existing users/channels or malformed commands
=> Handle more exceptions

debian/changelog, debian/control, requirements.txt, slack.py, slackclient/client.py
Fixes: https://github.com/ltworf/localslackirc/issues/214
Thanks to this, all requests are now asynchronous.
=> Async requests

Makefile, debian/changelog, debian/control, requirements.txt, slackclient/client.py, slackclient/http.py
=> Use my own async http client

slack.py
So things like `restricted_action` just show up directly in the IRC
client.
=> Pass only the error message rather than the entire http response

slackclient/http.py
For some reason python on a dead connection doesn't mention any
problem about writing on it, but then an exception comes when reading
the reply is attempted.
So this implements a better retry logic.
The retry is needed because of the connection pool, so we must be
prepared for a connection to be too old and not used for several
hours before it is attempted to reuse it.
=> Better retry when the connection fails

irc.py, slack.py, tests/test_re.py
so adding more settings doesn't make the constructor explode.
Of course it makes the constructor of the settings class explode, but
at least they don't have to be assigned to the self.bla variables.
=> Put all settings into a class

CHANGELOG, slack.py
It is very annoying to not have the feature.
At the moment it is still untested.
Closes: #252
=> Download history for IMs

irc.py
This slightly improves the readability of those messages.
=> irc: add a space after [deleted] and [botname]

irc.py, slack.py, tests/test_irc.py, tests/test_message_bot.py
reviewing will be easier commit by commit. commit messages explain the changes
=> Improve message formatting

irc.py, man/localslackirc.1
Also simplify parsing code for the setting
=> Document env var missing from man page

irc.py, mypy.conf, requirements.txt, slackclient/client.py
Since it has a vulnerability (of no consequence for this, anyway)
=> Use newer websockets version

irc.py
Also move a bit of code around
=> Make < and > work in the preformatted saved files

slack.py
=> Leave the user cache alone if the channel is unknown

CHANGELOG, README.md, irc.py, man/localslackirc.1, slack.py, slackclient/client.py
Generate typing notifications for users I want to annoy, when they
generate typing notifications.
=> Annoy users

CHANGELOG, README.md, irc.py, slack.py
=> Map threads to irc channels

slack.py
Just add the thread_ts field to the NoChanMessage and pass it along,
the rest is already handled.
Closes: #350
=> Place the message changes within the same thread

irc.py, slack.py
Fixes: #343
This will do replacements in the topic like in the incoming messages
so that mentions appearing in the topic will be resolved.
=> Parse topic

irc.py, slack.py
Otherwise escape and control sequences can end up in irc
=> Run the diff AFTER the slack stuff has been parsed

debian/changelog
=> Maintain changelog

CHANGELOG, README.md, irc.py, localslackirc.d/example, man/localslackirc.1, tests/test_irc.py
=> Silence entire channels rather than just users

slack.py
=> Ignore server disconnect

msgparsing.py, requirements.txt
=> emoji.emojize use_aliases=True => language="alias"

CHANGELOG, slack.py
This is much faster than creating a new one every time.
=> Use a single loader object

irc.py
For example, when irssi reconnects to localslackirc, it sends a command 'JOIN #chan1,#chan2'. Currently it fails as the channel '#chan1,#chan2' does not exist.
=> JOIN: command can take several channel names separated by comma

tests/test_diff.py
Can't reproduce, added test for it.
=> Add test for unreproducible error

Makefile, debian/changelog
=> Better clean target

CHANGELOG, irc.py
=> Saner behaviour for threads

CHANGELOG, irc.py, localslackirc.d/example, man/localslackirc.1
=> Rejoin channels on mention

CHANGELOG, irc.py, slack.py
=> Use the new API to open a /query

CHANGELOG, README.md, irc.py, man/localslackirc.1, msgparsing.py, slack.py
I want to automate reacting to messages, so that I can dislike
everything some people say, without effort.
=> Automatically react to messages

CHANGELOG, Makefile, lsi-getconf, man/lsi-getconf.1
=> Experimental script to extract token and cookie from firefox
